<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-31T19:55:55 IST" name="Default suite" finished-at="2021-12-31T19:57:59 IST" duration-ms="124245">
    <groups>
    </groups>
    <test started-at="2021-12-31T19:55:55 IST" name="Default test" finished-at="2021-12-31T19:57:59 IST" duration-ms="124245">
      <class name="com.testcase.Testcase">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.testcase.Testcase@6b8d96d9]" started-at="2021-12-31T19:55:45 IST" name="setup" finished-at="2021-12-31T19:55:55 IST" duration-ms="10223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Titletestcase()[pri:1, instance:com.testcase.Testcase@6b8d96d9]" started-at="2021-12-31T19:55:55 IST" name="Titletestcase" finished-at="2021-12-31T19:56:07 IST" duration-ms="11813" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Titletestcase -->
        <test-method signature="specificationtest()[pri:2, instance:com.testcase.Testcase@6b8d96d9]" started-at="2021-12-31T19:56:07 IST" name="specificationtest" finished-at="2021-12-31T19:56:26 IST" duration-ms="19230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- specificationtest -->
        <test-method signature="linkoftab()[pri:3, instance:com.testcase.Testcase@6b8d96d9]" started-at="2021-12-31T19:56:26 IST" name="linkoftab" finished-at="2021-12-31T19:56:26 IST" duration-ms="330" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [430.0] but found [431.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [430.0] but found [431.0]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at com.testcase.Testcase.linkoftab(Testcase.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- linkoftab -->
        <test-method signature="camera()[pri:4, instance:com.testcase.Testcase@6b8d96d9]" started-at="2021-12-31T19:56:26 IST" name="camera" finished-at="2021-12-31T19:57:19 IST" duration-ms="52254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- camera -->
        <test-method signature="musicalinstruments()[pri:5, instance:com.testcase.Testcase@6b8d96d9]" started-at="2021-12-31T19:57:19 IST" name="musicalinstruments" finished-at="2021-12-31T19:57:59 IST" duration-ms="40459" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- musicalinstruments -->
        <test-method signature="testvalidation()[pri:6, instance:com.testcase.Testcase@6b8d96d9]" started-at="2021-12-31T19:57:59 IST" name="testvalidation" finished-at="2021-12-31T19:57:59 IST" duration-ms="61" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testvalidation -->
      </class> <!-- com.testcase.Testcase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
